version: '3'
services:
  spring-boot-app:
    image: spring-boot-app-dummy
    ports:
      - "8080:8080"
    networks:
      - apisix-quickstart-net

networks:
  apisix-quickstart-net:
    external: true
