version: '3'
services:
  apisix:
    image: apache/apisix:3.8.0-debian
    ports:
      - "9080:9080"
      - "9443:9443"
    volumes:
      - ./conf:/usr/local/apisix/conf
    networks:
      - apisix-quickstart-net

  spring-boot-app:
    image: spring-boot-app-dummy
    ports:
      - "8081:8081"  # Assicurati che la porta qui corrisponda a quella configurata nel tuo server Spring Boot
    networks:
      - apisix-quickstart-net

networks:
  apisix-quickstart-net:
    external: true